### ISSUE TITLE
Chromecast wired connection not being discovered

### ISSUE THREAD

**Issue by Gr4cchus** [scyto/multicast-relay#10]
I'll have to triple check as I finalize more things, but the two times I tried to switch from the wifi connection to a wired connection on the same vlan it would not be discovered. Maybe it has something todo with igmp & pim on the switch because all the times I tried doing mDNS myself with an avahi vm, it would work or work much better with those two things disabled. Whereas with this project its the opposite, only works with igmp & pim; atleast in terms of devices connected through wifi I believe.

**Comment by scyto** [comment]
dunno, all my tests have been wired for sonos and wireless for chromecast
but in general start with all IGMP snooping off
also start with open firewalls   to test as there can be non-broadcast traffic involved.....

**Comment by scyto** [comment]
no followup - closing
