### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by PotatoHeadNY** [scyto/multicast-relay#12]
Would you happen to have any directions for setting this up on a firewalla gold? simular to the items listed here: [Firewalla Tutorial: Expanding With Docker Containers](https://help.firewalla.com/hc/en-us/articles/360053184374-Guide-Install-HomeBridge-on-Firewalla-)

**Comment by scyto** [comment]
Nope, sorry.
My recommendation is start with open firewall between the VLANs and the slowly restrict it until you dial it in.

In general if it is sonos on the IoT VLAN the sonos needs to make a TCP connection back into your LAN to the client requesting the streaming (yes i know that seems backwards but thats how it works) - basically you have to give the permission to make any inbound connection to LAN from VLAN it wants.  At which point IMHO its pointless putting it on a vlan....

**Comment by scyto** [comment]
no reply, closing
