### ISSUE TITLE
UDM Pro, Version 1.3.1, LocalTuya Discovery, and Docker Hub (Broadcast relay not working)

### ISSUE THREAD

**Issue by n8hjp** [scyto/multicast-relay#14]
First, thanks for your efforts on this up, along with Alsmith and anyone else involved. 

I set this (Well actually I used the Container you provided on Docker Hub) up on my UDM Pro and it was working for Multicasts, but not Broadcasts.    (For anyone searching, I was trying to get LocalTuya Discovery working on Home Assistant across subnets on the UDM Pro.)

It looks like Alsmith fixed this issue in PR#47:   https://github.com/alsmith/multicast-relay/pull/47 which is included in 1.3.1, but not 1.3.

The container you have on Docker Hub is running 1.3 which doesn't have this fix.     I edited the changes into the file in the container as described in the PR and broadcasts started working.   

Would you be willing to update the container on Docker Hub?     (Didn't see a way to ask for this on Docker Hub.)

**Comment by scyto** [comment]
if you are willing to test, sure!

**Comment by n8hjp** [comment]
Thanks...   Testing it is the least I can do!

**Comment by scyto** [comment]
cool, will try and do it this weekend

**Comment by scyto** [comment]
@n8hjp ok, just built it and pushed (i have not tested so YMMV) :-)

**Comment by n8hjp** [comment]
Cool, but if I run it like this on my UDM-ProI don't see the code changes I would expect in the container:

podman run -it -d  --name="multicast-relay" --network=host -e OPTS="--verbose --noMDNS --relay 255.255.255.255:25 255.255.255.255:5888 255.255.255.255:6666 255.255.255.255:6667" -e INTERFACES="br128 br20 br21" docker.io/scyto/multicast-relay

Here is the changes expected:

![Pasted Graphic 2](https://user-images.githubusercontent.com/63569764/178891385-45fe3e44-cf85-4d89-a851-e72544c50c93.png)

**Comment by scyto** [comment]
interesting, all my dockerfile does at build time is pull the main branch as-is (i make no changes to alsmith's code)

` && git clone --depth 1 https://github.com/alsmith/multicast-relay.git \`

is the code change in the main branch of that?

**Comment by scyto** [comment]
i just looked seems to be, assuming you want what is shown below?  if what is below is wrong then the PR never made it to live.

![image](https://user-images.githubusercontent.com/11369180/179056244-54f36103-d029-4718-8445-4aebda68ca1e.png)

guess i need to look whats in the container

**Comment by scyto** [comment]
i checked the code change you want is in the container at runtime.  It is.
You did refresh the image with a new pull right? :-)

This is the command to do a quick test pull and shell in to see `docker run -it --rm scyto/multicast-relay /bin/sh` i then installed nano rather than use cat.

![image](https://user-images.githubusercontent.com/11369180/179057468-9437cc36-4f3d-47b7-a17e-627f04568dea.png)

**Comment by n8hjp** [comment]
Sorry, did I mention I know just enough to be dangerous?       I know a little bit more more, I missed the pull part of getting the update, so of course I didn't see the changes.        And it looks good....    And seems to be working as expected.

**Comment by scyto** [comment]
no worries, easy to forget - if you have many containers you might want to use watchtower - it will update when new images come out (of course that can be a double edged sword :-) )

as its fixed, closing

**Comment by scyto** [comment]
closing, no update
