### ISSUE TITLE
Android clients don't see an mDNS devices, but iOS clients do

### ISSUE THREAD

**Issue by keonji** [scyto/multicast-relay#15]
I can't understand why it's going on. 

Before 1.12.22 on my UDM Pro, mDNS worked using default settings only in Default LAN and not in the VLAN network. After I installed 1.12.22, mDNS started work on both networks, but only for iOS clients. Android clients lose my mDNS devices. 

Then I switched all the mDNS settings off, stopped avahi-daemon, and tried your container. I faced the same problem. Only iOS clients can see the mDNS devices.

i'v tried to use this container https://hub.docker.com/r/stonith/udpbroadcastrelay how its advised in this thread https://community.ui.com/questions/UDMUDMP-IoT-VLAN-Speaker-Group-fix-with-mDNS-and-Google-Nest-Speakers-Chromecasts/ but it automatically stopping after several seconds.

**Comment by scyto** [comment]
sorry, no idea, i only have iOS devices and don't actually use my container at all

if i had to guess it maybe that the android client is using a different discovery mechanism, one way to tell is to open up your firewall between the LAN/VLANs and allow all trafffic.
