### ISSUE TITLE
Connection between multiple subnets and VPN

### ISSUE THREAD

**Issue by trailro** [scyto/multicast-relay#19]
Hello,

I am trying to have a single independent docker container that keeps the mdns relays and connection within my entire network, as this makes it easier to manage. Came across this one, but I am unsure if it will work or fit my model.

Currently I have the following set-up:
Site 1: managed by an UDM PRO
two lan networks (192.168.1.0/24, 192.168.2.0/24) no VLANs
openvpn link between site 1 and site 2 as site-to-site vpn (internal 10.30.0.1)

Site 2: managed by an USG
two lan networks (192.168.3.0/24, 192.168.4.0/24) no VLANs
openvpn link between site 1 and site 2 as site-to-site vpn (internal 10.30.0.2)

I have docker capability both at site 1 and site 2, but I would prefer running everything in site 1.

If I spawn a multicast-relay container in site 1 docker, I am sure, having read the documentation, that I can make it work for .1 and .2 networks. However, it is not clear to me if this would also work for the other two lan networks in site 2 over the vpn (provided that all ports are allowed to go through the VPN).

Current traceroute between the networks is as per above, single hop's.

traceroute from 192.168.1.143
traceroute to 192.168.3.2 (192.168.3.2), 64 hops max, 52 byte packets
 1  192.168.1.1  3.134 ms  2.326 ms  3.332 ms
 2  10.30.0.2  7.431 ms  7.796 ms  37.788 ms
 3  192.168.3.2  20.991 ms  11.867 ms  9.968 ms

Would this container work to have a single, central, relay for multicast so that all apple related kit in site 2 is available seamlessly in site 1 and all site 1 kit in site 2?

Many thanks.

**Comment by scyto** [comment]
you may find that multicast traffic can't go across some VPNs, but i am not sure.  if you got it working consider posting here.
