### ISSUE TITLE
Update docker image?

### ISSUE THREAD

**Issue by darizotas** [scyto/multicast-relay#3]
Hi @scyto ,

I have no found other mean of communication, I thought this would be the most appropriate even though there is no issue on the code. 
Have you considered creating a new docker image version? There are quite a few improvements in alsmith code repo. Yes, I could fork his/your code repo and create my own, but your repository is also included in udm-utilities code repo and I believe that forking would not help the community but myself.

Looking forward to your opinion.

Either way (positive or negative), you can close the issue.

Thanks!

**Comment by scyto** [comment]
Sure, i only do it when folks ask.
Would you be able to test?

**Comment by scyto** [comment]
@darizotas updated using the :test tag, can you test, you can use something like this on a UDMP to test with an ephemeral container
```docker run --rm -it --network=host -e OPTS="--verbose" -e INTERFACES="br0 br10" scyto/multicast-relay:test``` (you might need to replace docker with podman)

**Comment by darizotas** [comment]
Sure I can test. I will do so throughout the week, I do not have a UDMP with me now. @alsmith, would you be interested in cutting a release as well? Do you think the commits from the last release deserve a new tag?

Thanks @scyto !

**Comment by scyto** [comment]
@darizotas the docker :test tag includes alan's latest code from 9 days ago, how much newer do you want?  is there a specific PR you are wanting that's not in his main branch?
(i see no open PRs and only one open issue so i dont't there si anything newer we need from alan)

**Comment by darizotas** [comment]
Ok, I have not specific PRs... I just went through the different commits and I thought it could be interesting as some of them are bug fixes.

I will let you know the outcome.

**Comment by alsmith** [comment]
v1.3 released - https://github.com/alsmith/multicast-relay/releases/tag/v1.3

**Comment by darizotas** [comment]
@scyto I tested successfully multicast-relay v1.3 as @alsmith recently published.

Test environment:
udmpro firmware 1.8.4

Test cases:
google chromecast (spotify, google home, youtube)
sonos (spotify, sonos app)
some other IoT gadgets via SSDP

You can promote test to latest :)

Many, many thanks to both fo you for this. I hope the rest (e.g. udm-utilities community) will benefit from this.

**Comment by scyto** [comment]
@darizotas to be clear, you pulled the container marked test and tested it  vs downloading and running v1.3 code manually.
I am unclear from your answer above.

**Comment by scyto** [comment]
> v1.3 released - https://github.com/alsmith/multicast-relay/releases/tag/v1.3

Thanks, can I assume this didn't change the code in the master ropo - just tagged it?
I ask because i did a rebuild and it didn't seem the code changed between today and 2 days ago :-)

**Comment by darizotas** [comment]
@scyto, I just pulled the container marked as test. However, I assumed that I could link it to multicast-relay v1.3, as you indicate in your previous comment, because there were no commits in between. @alsmith reacted very quickly to my comment when I tagged him.

I hope this can clarify my previous answer, so that you can promote test to latest (linked to v1.3) and that you can consider this issue closed.

Thank you both!

**Comment by scyto** [comment]
It has the latest code you see on master on github.
That's all i can tell you.
Either way can you, as i have asked multiple times, test the container in test.

I don't care what it has it in it, you asked me to create a container with the latest, i have done that. 
Please test otherwise you are wasting my time.

**Comment by scyto** [comment]
actually forget it, it works on mine, i promoted to latest anyway.
Closing.

**Comment by darizotas** [comment]
I think, you did not read properly my message or I just did not communicate it properly. I did test your container tagged as "test". I did not do any other thing.

All in all, you did not waste your time nor mine and the community will benefit from this.

Thanks
