### ISSUE TITLE
Multiple Multicast Networks?

### ISSUE THREAD

**Issue by VeniceNerd** [scyto/multicast-relay#8]
Is it possible to connect multiple sets of vlans together? I will have my network (1), my tenant network (2), and a shared iot network (3). 

I would want network 1 and 3 to share mdns as well as network 2 and 3 to share mdns. However, I don’t want network 1 and 2 to share mdns with each other. 

Is that possible?

**Comment by scyto** [comment]
No idea, best asked on the main project page. Possibly running two instances might work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: VeniceNerd ***@***.***>
Sent: Friday, November 12, 2021 9:50:18 PM
To: scyto/multicast-relay ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [scyto/multicast-relay] Multiple Multicast Networks? (Issue #8)


Is it possible to connect multiple sets of vlans together? I will have my network (1), my tenant network (2), and a shared iot network (3).

I would want network 1 and 3 to share mdns as well as network 2 and 3 to share mdns. However, I don’t want network 1 and 2 to share mdns with each other.

Is that possible?

**Comment by VeniceNerd** [comment]
It seems there is a way doing it with "ifFilter.json". Here is a link to the discussion for anyone else interested:

https://github.com/alsmith/multicast-relay/issues/59
