### ISSUE TITLE
Installed Multicast-Relay but it doesn't appear to run...

### ISSUE THREAD

**Issue by VeniceNerd** [scyto/multicast-relay#9]
I just installed "on-boot-script" and "container-common" on my UDM Pro. Placed my "20-container-common.sh" and "30-multicast-relay.sh" into "/mnt/data/on_boot." and my "ifFilter.json" in "/mnt/data/on_boot.d_support".

Then I ran the following command to install your "multicast-relay":

```
podman run -it -d \
--restart=on-failure:10 \
--name="multicast-relay" \
--network=host \
--mount type=bind,src=/mnt/data/on_boot.d_support,dst=/multicast-relay-config \
-e OPTS="--ifFilter=/multicast-relay-config/ifFilter.json" \
-e INTERFACES="br0 br10 br20 br30 br50" \
docker.io/scyto/multicast-relay
```

<img width="569" alt="144343027-e7ad37b6-ae33-414e-8043-ec99aca525ef" src="https://user-images.githubusercontent.com/25128243/144348216-206acd8a-b0eb-4d10-9d69-d29ff94c2a42.png">

Followed by these two commands:

```
killall avahi-daemon

podman start multicast-relay
```

<img width="569" alt="144343360-af3042ce-dd5a-4df8-923a-077057719d0b" src="https://user-images.githubusercontent.com/25128243/144348285-59a941a2-c4f4-4cfe-8b9a-5acf7a577f15.png">

There were no error messages or anything but running Discovery tool on a computer on my VLAN10 does not show any devices from my VLAN50. So it looks like nothing actually happened after I installed the multicast relay.

I ran "podman ps" and got the following result:
<img width="776" alt="144347563-00012e93-fe88-4a20-86ec-0df136197ad3" src="https://user-images.githubusercontent.com/25128243/144348466-2ef4bc82-4fbb-4112-af9b-66878594d927.png">

I'm a n00b so I'm not sure if "podman ps" should actually be showing my "multicast-reay" instance or not but if it should then something is definitely wrong.

Do you have any idea what may have gone wrong here and what I could do to trouble shoot? 

EDIT 1:

After digging trough some forums I found this command "journalctl -u udm-boot.service" and ran it from the Unifi Shell. Not 100% sure what it does but here is the log result:

<img width="852" alt="Screenshot 2021-12-01 at 21 41 49" src="https://user-images.githubusercontent.com/25128243/144364594-08c0406d-1029-46f7-9bdd-9130b6b5381e.png">

**Comment by scyto** [comment]
Dunno, use the verbose option and remove the detached option so you see console output?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: VeniceNerd ***@***.***>
Sent: Wednesday, December 1, 2021 6:49:08 PM
To: scyto/multicast-relay ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [scyto/multicast-relay] Installed Multicast-Relay but it doesn't appear to run... (Issue #9)


I just installed "on-boot-script" and "container-common" on my UDM Pro. Placed my "20-container-common.sh" and "30-multicast-relay.sh" into "/mnt/data/on_boot." and my "ifFilter.json" in "/mnt/data/on_boot.d_support".

Then I ran the following command to install the "multicast-relay":

podman run -it -d \
--restart=on-failure:10 \
--name="multicast-relay" \
--network=host \
--mount type=bind,src=/mnt/data/on_boot.d_support,dst=/multicast-relay-config \
-e OPTS="--ifFilter=/multicast-relay-config/ifFilter.json" \
-e INTERFACES="br0 br10 br20 br30 br50" \
docker.io/scyto/multicast-relay


[144343027-e7ad37b6-ae33-414e-8043-ec99aca525ef]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25128243%2F144348216-206acd8a-b0eb-4d10-9d69-d29ff94c2a42.png&data=04%7C01%7C%7Cb29afb78d97b40259ea108d9b53e5048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740101504542201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Gk954chPLamoMHx2nBZ%2FytdC63LK%2FwpURUllAqzjJos%3D&reserved=0>

Followed by these two commands:

killall avahi-daemon

podman start multicast-relay


[144343360-af3042ce-dd5a-4df8-923a-077057719d0b]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25128243%2F144348285-59a941a2-c4f4-4cfe-8b9a-5acf7a577f15.png&data=04%7C01%7C%7Cb29afb78d97b40259ea108d9b53e5048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740101504552198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LnwRbJwtkKWLML9dmjbij2jFEaFZ00c3%2BpDp0gfmupY%3D&reserved=0>

There were no error messages or anything but running Discovery tool on a computer on my VLAN10 does not show any devices from my VLAN50. So it looks like nothing actually happened after I installed the multicast relay.

I ran "podman ps" and got the following result:
[144347563-00012e93-fe88-4a20-86ec-0df136197ad3]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25128243%2F144348466-2ef4bc82-4fbb-4112-af9b-66878594d927.png&data=04%7C01%7C%7Cb29afb78d97b40259ea108d9b53e5048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740101504552198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xgliDjKpJTZ1QoI%2BSHCz7WnDSjEG0VZLWV%2BnDdzNNO8%3D&reserved=0>

I'm a n00b so I'm not sure if "podman ps" should actually be showing my "multicast-reay" instance or not but if it should then something is definitely wrong.

Do you have any idea what may have gone wrong here and what I could do to trouble shoot?

**Comment by VeniceNerd** [comment]
I'm extremely new to this. So would I just run the same "podman run -it -d \" command again? I don't want to end up with two instances with multicast relay running or something weird like that.

So would I just run this again?

```
podman run -it -d \
--restart=on-failure:10 \
--name="multicast-relay" \
--network=host \
--mount type=bind,src=/mnt/data/on_boot.d_support,dst=/multicast-relay-config \
-e OPTS=" --verbose"
-e OPTS="--ifFilter=/multicast-relay-config/ifFilter.json" \
-e INTERFACES="br0 br10 br20 br30 br50" \
docker.io/scyto/multicast-relay
```

I added the verbose line in there but don't know what you mean by  "remove the detached option".

Thanks a lot!

**Comment by scyto** [comment]
It's documented in my instructions how to run with console output....

Anyhoo -d means detach from console, -it means create an interactive tty.

**Comment by scyto** [comment]
In terms of the error does it disappear if you remove the i filter.json option? If it does then it is your json file at issue.

**Comment by VeniceNerd** [comment]
> In terms of the error does it disappear if you remove the i filter.json option? If it does then it is your json file at issue.

Yes!!! That was it! There was a mistake in my "ifFilter.json". After I fixed that everything runs. Unfortunately it seems like the ifFilter.json is not actually doing anything atm since I'm seeing all devices from all VLANS on all other VLANS but at least I am one step further. Thank you! 

> Anyhoo -d means detach from console, -it means create an interactive tty.

Thank you. Just out of curiosity (and please ignore if you don't have time to teach) why would it be beneficial to run a container attached vs detached? Same goes for the interactive tty. What does it actually do? Again, ignore if you don't have time. I'm just trying to learn little by little so I don't just use stuff I see online. ;)

**Comment by scyto** [comment]
https://docs.docker.com/engine/reference/commandline/exec/  because some processes expect to run in a tty, and sometimes because you want to attach to it later when it is running....
